---
- name: Configuring apache2
  hosts: all
  tasks:
    - name: all child playbooks
      include_tasks: "{{item}}"
      with_items:
       - install.yml
       - edit_index.yml
       - restart.yml
       - check_url_response.yml
...
