---
- name: Implementing Handlers
  hosts: all
  tasks: 
    - name: Install Apache2
      apt:
        name: apache2
        state: present
      notify: Check url response
    - name: Edit the index.html
      copy: 
       content: " Handlers implement of Ansible-Home Page"
       dest: /var/www/html/index.html
      notify: Restart apache2
  handlers:
    - name: Restart apache2
      service: 
       name: apache2
       state: restarted
    - name: Check url response
      uri:
        url: "{{item}}"
        status_code: 200
      with_items:
        - http://172.31.7.251
        - http://172.31.3.190



...
