---
- name: Create multiple users and copy files or dirs into the users home dir
  hosts: all
  tasks:
    - name: Create users
      user:
        name: "{{item.a}}"
        password: "{{item.b}}"
        home: "{{item.c}}"
      with_items:
        - {a: Usha, b: welcome, c: /home/ubuntu/Usha}
        - {a: Ravi, b: welcome, c: /home/Ravi}
    - name: Copy file or dirs into users home dir
      copy:
        src: "{{item.a}}"
        dest: "{{item.b}}"
      with_items:
        - {a: /etc/passwd, b: /home/ubuntu/Usha}
        - {a: /etc/group, b: /home/Ravi}


...
