---
- name: Configuring Apache2
  hosts: all
  tasks:
    - name: Install Apache2
      apt:
        name: apache2
        state: present
       
    - name: Edit the index.html file
      copy:
        content: "Apache Home Page"
        dest: /var/www/html/index.html
    
    - name: Restart Apache2
      service:
        name: apache2
        state: restarted
    - name: Pause for 1 min
      pause:
        minutes: 1
    - name: Check response  of tomcat on server1
      uri: 
        url: http://172.31.7.251:9090
        status_code: 200
    - name: Check response of tomcat on server2
      uri:
        url: http://172.31.3.190:9090
        status_code: 200
        


...
