---
- name: Install software applications
  hosts: all
  vars:
    - a: tomcat9
    - b: present
    - c: yes
  tasks:
    - name: Install/uninstall  software
      apt:
        name: "{{a}}"
        state: "{{b}}"
        update_cache: "{{c}}"

...
