---
- name: Check if tomcat9 is present , if not install  tomcat10
  hosts: all
  tasks:
    - name: Tomcat9 checkup
      apt:
        name: tomcat9
        state: present
        update_cache: yes
      register: a
    - name: Display output of above modules
      debug: 
       var: a 
    - name: Install tomcat10 if tomacat9 is not present
      apt:
        name: tomcat10
        state: present
      when: a.changed == true
